### 회원가입
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "userEmail": "user1",
  "userPassword": "test",
  "userRole": "ROLE_USER"
}

### 로그인
GET http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "user1",
  "password": "test"
}

### 인가요청
GET http://localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJ1c2VyX25hbWUiOiJ1c2VyMSIsImlzcyI6ImppeW9uZyIsImV4cGlyZWRfZGF0ZSI6MTcwNzc4OTU5NH0.nDL0ZQVbCu_uwO_2LrSpvkAhVAg9dzHWMWQ_DhyCAqo